# Generated by Django 5.1.1 on 2024-12-03 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
        ('hospital', '0005_blooddonationcampschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('camp_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.blooddonationcampschedule')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.userprofile')),
            ],
        ),
    ]
