# Generated by Django 5.1.1 on 2024-12-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsent',
            name='is_consent_given',
        ),
    ]
