# Generated by Django 5.1.1 on 2024-11-29 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the scheduled donation')),
                ('time', models.TimeField(help_text='Time of the scheduled donation')),
                ('location', models.CharField(help_text='Location of the blood donation', max_length=255)),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the user is available for donation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_schedules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
