# Generated by Django 5.1.1 on 2024-12-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_remove_userconsent_is_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='is_consent_given',
            field=models.BooleanField(default=False, help_text='Indicates if the user has given consent.'),
        ),
    ]
