# Generated by Django 5.1.1 on 2024-11-29 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id_proofs/')),
                ('willing_to_donate_blood', models.BooleanField(default=False)),
                ('willing_to_donate_organs', models.BooleanField(default=False)),
                ('specific_organs', models.JSONField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DonorProfile',
        ),
    ]
