# Generated by Django 5.1.1 on 2024-12-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_blooddonationregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonationregistration',
            old_name='camp_schedule',
            new_name='camp',
        ),
        migrations.RenameField(
            model_name='blooddonationregistration',
            old_name='registration_date',
            new_name='registered_at',
        ),
        migrations.RenameField(
            model_name='blooddonationregistration',
            old_name='donor',
            new_name='user',
        ),
    ]
