# Generated by Django 5.1.1 on 2024-11-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_remove_donorprofile_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='willing_to_donate_organs',
            field=models.BooleanField(),
        ),
    ]
