# Generated by Django 5.1.1 on 2024-11-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_userdetails_delete_donorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
