# Generated by Django 5.1.1 on 2024-12-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_rename_camp_schedule_blooddonationregistration_camp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blooddonationregistration',
            old_name='registered_at',
            new_name='registration_date',
        ),
    ]
