# Generated by Django 5.1.1 on 2024-12-30 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_alter_userconsent_is_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsent',
            name='signimage',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Upload an image related to your consent.', upload_to='signimages/'),
            preserve_default=False,
        ),
    ]
