# Generated by Django 5.1.1 on 2025-01-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_userconsent_signimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
