# Generated by Django 5.1.1 on 2024-12-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_donorresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorresponse',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
