# Generated by Django 5.1.1 on 2024-11-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='willing_to_donate_organ',
            field=models.BooleanField(),
        ),
    ]
