# Generated by Django 5.1.1 on 2024-12-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_alter_donorresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organ_donor',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_blood_donor',
            field=models.BooleanField(default=False),
        ),
    ]
