# Generated by Django 5.1.1 on 2024-12-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_remove_user_is_organ_donor_alter_user_is_blood_donor'),
        ('hospital', '0002_emergencydonationalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('donor', 'Donor'), ('hospital', 'Hospital')], help_text='Indicates whether the sender is a donor or hospital.', max_length=10)),
                ('sender_name', models.CharField(help_text='Name of the sender (donor or hospital).', max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(help_text='The hospital involved in the chat.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='hospital.hospital')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
