# Generated by Django 5.1.1 on 2024-12-24 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(help_text='Upload your certificate in PDF format.', upload_to='certificates/')),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('is_consent_given', models.BooleanField(default=False, help_text='Indicates if the user has given consent.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
            },
        ),
    ]
