# Generated by Django 5.1.1 on 2024-12-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_donorresponse_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorResponse',
        ),
    ]
