# Generated by Django 5.1.1 on 2024-12-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_delete_donorresponse'),
        ('hospital', '0002_emergencydonationalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_message', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hospital.emergencydonationalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.userprofile')),
            ],
            options={
                'unique_together': {('user', 'alert')},
            },
        ),
    ]
