# Generated by Django 5.1.1 on 2024-12-24 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0015_alter_consentcertificate_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentcertificate',
            name='consent_certificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to='consent_certificate/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consentcertificate',
            name='user_profile',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='consent_certificate', to='donor.userprofile'),
            preserve_default=False,
        ),
    ]
