# Generated by Django 5.1.1 on 2024-12-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0016_alter_consentcertificate_consent_certificate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsentCertificate',
        ),
    ]
