# Generated by Django 5.1.1 on 2024-12-24 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_delete_consentcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_certificate', models.FileField(upload_to='consent_certificate/')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_certificate', to='donor.userprofile')),
            ],
        ),
    ]
