# Generated by Django 5.1.1 on 2024-12-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_consentcertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsentCertificate',
        ),
    ]
