# Generated by Django 5.1.1 on 2024-11-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
