# Generated by Django 5.1.1 on 2024-12-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_blooddonationschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodDonationSchedule',
        ),
    ]
